In [1]:
import pandas as pd

In [2]:
hotel=pd.read_csv('Hotel_Reviews.csv')
hotel.head()

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/17,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/17,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0,52.360576,4.915968
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/17,7.7,Hotel Arena,Australia,Rooms are nice but for elderly a bit difficul...,42,1403,Location was good and staff were ok It is cut...,21,9,7.1,"[' Leisure trip ', ' Family with young childre...",3,52.360576,4.915968
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/17,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3,52.360576,4.915968
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/24/17,7.7,Hotel Arena,New Zealand,You When I booked with your company on line y...,140,1403,Amazing location and building Romantic setting,8,3,6.7,"[' Leisure trip ', ' Couple ', ' Suite ', ' St...",10,52.360576,4.915968

In [3]:
ukhotel=hotel.loc[hotel['Reviewer_Nationality']==' United Kingdom ']
len(ukhotel)

245246

In [4]:
ukhotel.reset_index(drop=True,inplace=True)

In [5]:
from typing import List
def lower(lines: List[str]):
    '''return all characters in lowercase'''
    return [line.lower() for line in lines]

In [6]:
ukhotel['Lower_Neg_Review'] = lower(ukhotel['Negative_Review'])
ukhotel['Lower_Pos_Review'] = lower(ukhotel['Positive_Review'])

/var/folders/dj/cfyl0fm563bghvxvcfcp4pb40000gn/T/ipykernel_70568/1967808757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ukhotel['Lower_Neg_Review'] = lower(ukhotel['Negative_Review'])
/var/folders/dj/cfyl0fm563bghvxvcfcp4pb40000gn/T/ipykernel_70568/1967808757.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ukhotel['Lower_Pos_Review'] = lower(ukhotel['Positive_Review'])

In [7]:
# Find the most common words
from collections import Counter
import nltk
from nltk.corpus import stopwords
counter=Counter()
for review in ukhotel['Lower_Pos_Review']:
    words = nltk.word_tokenize(review)  # "words" still contains punctuations
    for word in words:
        counter[word]+=1
top100pos=counter.most_common(100)
top100pos

[('the', 231683),
 ('and', 205049),
 ('was', 121272),
 ('staff', 98958),
 ('very', 89616),
 ('to', 82466),
 ('a', 81896),
 ('location', 81045),
 ('room', 70800),
 ('hotel', 57531),
 ('were', 55097),
 ('in', 51610),
 ('good', 50849),
 ('of', 49917),
 ('great', 49772),
 ('for', 49007),
 ('friendly', 44212),
 ('helpful', 38842),
 ('breakfast', 36786),
 ('we', 36686),
 ('excellent', 33313),
 ('clean', 32297),
 ('comfortable', 31011),
 ('with', 30594),
 ('bed', 29117),
 ('is', 29027),
 ('i', 26709),
 ('lovely', 26601),
 ('it', 26221),
 ('nice', 25581),
 ('no', 20327),
 ('from', 19469),
 ('on', 19144),
 ('rooms', 17938),
 ('all', 17488),
 ('stay', 17049),
 ('our', 16975),
 ('at', 16880),
 ('positive', 15915),
 ('comfy', 15669),
 ('had', 15236),
 ('really', 15114),
 ('but', 14697),
 ('as', 14462),
 ('so', 14270),
 ('you', 13690),
 ('this', 12162),
 ('everything', 12083),
 ('service', 12036),
 ('are', 11912),
 ('amazing', 11871),
 ('my', 11797),
 ('bar', 11664),
 ('well', 11213),
 ('not', 10973),
 ('would', 10781),
 ('t', 10570),
 ('close', 10423),
 ('quiet', 10401),
 ('perfect', 10144),
 ('have', 10014),
 ('fantastic', 9806),
 ('which', 9712),
 ('station', 9705),
 ('facilities', 9660),
 ('london', 9628),
 ('us', 9365),
 ('food', 9304),
 ('walk', 9199),
 ('there', 8781),
 ('reception', 8554),
 ('that', 8374),
 ('again', 8368),
 ('out', 8334),
 ('bathroom', 8330),
 ('beds', 8216),
 ('modern', 8083),
 ('an', 8067),
 ('view', 7969),
 ('be', 7745),
 ('they', 7711),
 ('shower', 7622),
 ('also', 7521),
 ('area', 7338),
 ('free', 7334),
 ('spacious', 7128),
 ('easy', 7011),
 ('s', 6781),
 ('beautiful', 6656),
 ('tube', 6650),
 ('just', 6648),
 ('central', 6583),
 ('too', 6457),
 ('loved', 6379),
 ('restaurant', 6010),
 ('extremely', 5963),
 ('value', 5953),
 ('definitely', 5806),
 ('will', 5737),
 ('check', 5538)]

In [8]:
# Find the most common words
for review in ukhotel['Lower_Neg_Review']:
    words = nltk.word_tokenize(review)  # "words" still contains punctuations
    for word in words:
        counter[word]+=1
top100neg=counter.most_common(100)
top100neg

[('the', 474002),
 ('and', 313240),
 ('was', 244770),
 ('a', 200349),
 ('to', 195418),
 ('room', 155588),
 ('in', 132284),
 ('very', 128753),
 ('staff', 118479),
 ('no', 112302),
 ('of', 110224),
 ('for', 106975),
 ('we', 88973),
 ('were', 88959),
 ('hotel', 88922),
 ('location', 85348),
 ('i', 84597),
 ('it', 76994),
 ('not', 66738),
 ('breakfast', 66433),
 ('good', 60811),
 ('negative', 59882),
 ('on', 56916),
 ('with', 55743),
 ('great', 55026),
 ('is', 54813),
 ('but', 52339),
 ('t', 51855),
 ('had', 49587),
 ('at', 46961),
 ('friendly', 45930),
 ('bed', 44176),
 ('helpful', 40849),
 ('as', 40271),
 ('have', 38340),
 ('from', 37420),
 ('clean', 35721),
 ('our', 34935),
 ('that', 34761),
 ('excellent', 34641),
 ('so', 34286),
 ('comfortable', 33334),
 ('this', 31975),
 ('rooms', 31914),
 ('all', 31744),
 ('there', 30769),
 ('you', 30321),
 ('nice', 30307),
 ('my', 29984),
 ('would', 29314),
 ('be', 29173),
 ('lovely', 28304),
 ('stay', 25968),
 ('which', 24600),
 ('nothing', 24562),
 ('bar', 24496),
 ('small', 24470),
 ('they', 24391),
 ('out', 22861),
 ('really', 22741),
 ('are', 22111),
 ('could', 22004),
 ('when', 21658),
 ('service', 21624),
 ('bathroom', 20898),
 ('us', 19339),
 ('only', 18971),
 ('an', 18850),
 ('too', 18794),
 ('didn', 18308),
 ('shower', 18047),
 ('one', 17548),
 ('night', 17434),
 ('reception', 17019),
 ('everything', 16418),
 ('comfy', 16300),
 ('little', 16139),
 ('positive', 16006),
 ('also', 15841),
 ('been', 15821),
 ('food', 15801),
 ('like', 15141),
 ('get', 14913),
 ('s', 14891),
 ('just', 14711),
 ('facilities', 14609),
 ('well', 14599),
 ('if', 14436),
 ('bit', 14336),
 ('up', 14007),
 ('more', 13830),
 ('or', 13727),
 ('view', 13357),
 ('by', 12932),
 ('area', 12882),
 ('london', 12811),
 ('check', 12768),
 ('again', 12722),
 ('close', 12525),
 ('amazing', 12430)]

In [9]:
len(ukhotel[ukhotel['days_since_review']<365])

124881

In [10]:
uk=ukhotel[ukhotel['days_since_review']<365]
uk.reset_index(drop=True,inplace=True)
uk.head()

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng,Lower_Neg_Review,Lower_Pos_Review
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/17,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,26,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3,52.360576,4.915968,my room was dirty and i was afraid to walk ba...,great location in nice surroundings the bar a...
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Cleaner did not change our sheet and duvet ev...,33,1403,The room is spacious and bright The hotel is ...,18,6,4.6,"[' Leisure trip ', ' Group ', ' Duplex Twin Ro...",17,52.360576,4.915968,cleaner did not change our sheet and duvet ev...,the room is spacious and bright the hotel is ...
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Apart from the price for the brekfast Everyth...,11,1403,Good location Set in a lovely park friendly s...,19,1,10.0,"[' Leisure trip ', ' Couple ', ' Duplex Double...",17,52.360576,4.915968,apart from the price for the brekfast everyth...,good location set in a lovely park friendly s...
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/7/17,7.7,Hotel Arena,United Kingdom,Nothing all great,5,1403,Rooms were stunningly decorated and really sp...,101,2,10.0,"[' Leisure trip ', ' Group ', ' Duplex Double ...",27,52.360576,4.915968,nothing all great,rooms were stunningly decorated and really sp...
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/6/17,7.7,Hotel Arena,United Kingdom,The floor in my room was filfy dirty Very bas...,28,1403,Comfy bed good location,6,7,4.6,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",28,52.360576,4.915968,the floor in my room was filfy dirty very bas...,comfy bed good location

In [11]:
from textacy.preprocessing.replace import urls, hashtags, numbers, emails, emojis, currency_symbols
uk["Positive_Review_Clean"] = uk['Lower_Pos_Review'].\
  apply(urls).\
  apply(hashtags).\
  apply(numbers).\
  apply(currency_symbols).\
  apply(emojis).\
  apply(emails)
uk["Negative_Review_Clean"] = uk['Lower_Neg_Review'].\
  apply(urls).\
  apply(hashtags).\
  apply(numbers).\
  apply(currency_symbols).\
  apply(emojis).\
  apply(emails)
uk.head(5)

/var/folders/dj/cfyl0fm563bghvxvcfcp4pb40000gn/T/ipykernel_70568/3649171310.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uk["Positive_Review_Clean"] = uk['Lower_Pos_Review'].\
/var/folders/dj/cfyl0fm563bghvxvcfcp4pb40000gn/T/ipykernel_70568/3649171310.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uk["Negative_Review_Clean"] = uk['Lower_Neg_Review'].\

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,...,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng,Lower_Neg_Review,Lower_Pos_Review,Positive_Review_Clean,Negative_Review_Clean
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/17,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,...,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3,52.360576,4.915968,my room was dirty and i was afraid to walk ba...,great location in nice surroundings the bar a...,great location in nice surroundings the bar a...,my room was dirty and i was afraid to walk ba...
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Cleaner did not change our sheet and duvet ev...,33,1403,The room is spacious and bright The hotel is ...,...,6,4.6,"[' Leisure trip ', ' Group ', ' Duplex Twin Ro...",17,52.360576,4.915968,cleaner did not change our sheet and duvet ev...,the room is spacious and bright the hotel is ...,the room is spacious and bright the hotel is ...,cleaner did not change our sheet and duvet ev...
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Apart from the price for the brekfast Everyth...,11,1403,Good location Set in a lovely park friendly s...,...,1,10.0,"[' Leisure trip ', ' Couple ', ' Duplex Double...",17,52.360576,4.915968,apart from the price for the brekfast everyth...,good location set in a lovely park friendly s...,good location set in a lovely park friendly s...,apart from the price for the brekfast everyth...
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/7/17,7.7,Hotel Arena,United Kingdom,Nothing all great,5,1403,Rooms were stunningly decorated and really sp...,...,2,10.0,"[' Leisure trip ', ' Group ', ' Duplex Double ...",27,52.360576,4.915968,nothing all great,rooms were stunningly decorated and really sp...,rooms were stunningly decorated and really sp...,nothing all great
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/6/17,7.7,Hotel Arena,United Kingdom,The floor in my room was filfy dirty Very bas...,28,1403,Comfy bed good location,...,7,4.6,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",28,52.360576,4.915968,the floor in my room was filfy dirty very bas...,comfy bed good location,comfy bed good location,the floor in my room was filfy dirty very bas...

In [12]:
from textacy.preprocessing.remove import punctuation
uk['Positive_Review_Clean'].apply(punctuation)
uk['Negative_Review_Clean'].apply(punctuation)
uk.head()

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,...,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng,Lower_Neg_Review,Lower_Pos_Review,Positive_Review_Clean,Negative_Review_Clean
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/31/17,7.7,Hotel Arena,United Kingdom,My room was dirty and I was afraid to walk ba...,210,1403,Great location in nice surroundings the bar a...,...,1,3.8,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",3,52.360576,4.915968,my room was dirty and i was afraid to walk ba...,great location in nice surroundings the bar a...,great location in nice surroundings the bar a...,my room was dirty and i was afraid to walk ba...
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Cleaner did not change our sheet and duvet ev...,33,1403,The room is spacious and bright The hotel is ...,...,6,4.6,"[' Leisure trip ', ' Group ', ' Duplex Twin Ro...",17,52.360576,4.915968,cleaner did not change our sheet and duvet ev...,the room is spacious and bright the hotel is ...,the room is spacious and bright the hotel is ...,cleaner did not change our sheet and duvet ev...
2,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/17/17,7.7,Hotel Arena,United Kingdom,Apart from the price for the brekfast Everyth...,11,1403,Good location Set in a lovely park friendly s...,...,1,10.0,"[' Leisure trip ', ' Couple ', ' Duplex Double...",17,52.360576,4.915968,apart from the price for the brekfast everyth...,good location set in a lovely park friendly s...,good location set in a lovely park friendly s...,apart from the price for the brekfast everyth...
3,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/7/17,7.7,Hotel Arena,United Kingdom,Nothing all great,5,1403,Rooms were stunningly decorated and really sp...,...,2,10.0,"[' Leisure trip ', ' Group ', ' Duplex Double ...",27,52.360576,4.915968,nothing all great,rooms were stunningly decorated and really sp...,rooms were stunningly decorated and really sp...,nothing all great
4,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,7/6/17,7.7,Hotel Arena,United Kingdom,The floor in my room was filfy dirty Very bas...,28,1403,Comfy bed good location,...,7,4.6,"[' Leisure trip ', ' Solo traveler ', ' Duplex...",28,52.360576,4.915968,the floor in my room was filfy dirty very bas...,comfy bed good location,comfy bed good location,the floor in my room was filfy dirty very bas...

In [13]:
uk.to_csv('uk_hotel.csv',index=False)